# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-09 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign',
            new_name='SignUp',
        ),
    ]
