# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-09 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20170709_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
