# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_remove_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
