# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_auto_20170711_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
