# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-18 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_auto_20170718_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='detail',
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
